#!/bin/bash
set -e

START_TIME=$(date +%s)

# Input Root
TEST_SET="test_aug"
RUN_EVAL="false"
MONITOR_GPU="false"

while [[ $# -gt 0 ]]; do
    case $1 in
        --test_set)
            TEST_SET="$2"
            shift 2
            ;;
        --run_eval)
            RUN_EVAL="$2"
            shift 2
            ;;
        --monitor_gpu)
            MONITOR_GPU="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: bash run_pipeline.sh --test_set [test_raw|test_aug] --run_eval [true|false] --monitor_gpu [true|false]"
            exit 1
            ;;
    esac
done

if [[ "$TEST_SET" != "test_raw" && "$TEST_SET" != "test_aug" ]]; then
    echo "TEST_SET must be test_raw or test_aug"
    exit 1
fi

if [[ "$RUN_EVAL" != "true" && "$RUN_EVAL" != "false" ]]; then
    echo "RUN_EVAL must be true or false"
    exit 1
fi

if [[ "$MONITOR_GPU" != "true" && "$MONITOR_GPU" != "false" ]]; then
    echo "MONITOR_GPU must be true or false"
    exit 1
fi


# =========================
# GPU Memory Monitor
# =========================

GPU_ID=0
GPU_MONITOR_INTERVAL=0.05
GPU_MEMORY_LOG="./peak_gpu_memory.log"
GPU_MONITOR_PID=""

monitor_gpu_memory() {
    while true; do
        MEM=$(nvidia-smi --id=${GPU_ID} \
            --query-gpu=memory.used \
            --format=csv,noheader,nounits 2>/dev/null | head -n 1)

        if [[ -n "$MEM" ]]; then
            echo "$MEM" >> ${GPU_MEMORY_LOG}
        fi

        sleep ${GPU_MONITOR_INTERVAL}
    done
}

cleanup() {
    if [[ -n "$GPU_MONITOR_PID" ]]; then
        kill ${GPU_MONITOR_PID} 2>/dev/null || true
    fi
}

trap cleanup EXIT

if [[ "$MONITOR_GPU" = "true" ]]; then
    echo "0" > ${GPU_MEMORY_LOG}
    monitor_gpu_memory &
    GPU_MONITOR_PID=$!
fi


# =========================
# Paths
# =========================

DATASET_DIR="./dataset"

MODEL="./detection/models/YOLO11L_SDA.pt"

IMAGE_DIR="${DATASET_DIR}/images/${TEST_SET}"

# Select dataset YAML
if [[ "$TEST_SET" = "test_aug" ]]; then
    DATA_YAML="${DATASET_DIR}/meta_aug.yaml"
else
    DATA_YAML="${DATASET_DIR}/meta_raw.yaml"
fi

# Detection output generated by detection/test.py
DET_OUTPUT="./detection/runs/detect/test_YOLO11L_SDA"

# Other outputs
CROP_OUTPUT="./crop/output"
CLS_OUTPUT="./classification/output"
ORDER_OUTPUT="./ordering/output_ours"
ORDER_CSV="./evaluation_results"


echo "Seal-Robust-KCR Inference Pipeline"
echo "Test Set: ${TEST_SET}"
echo "Dataset YAML: ${DATA_YAML}"
echo "Evaluation: ${RUN_EVAL}"
echo "Monitor GPU: ${MONITOR_GPU}"
echo "GPU ID: ${GPU_ID}"


# =========================
# Check files
# =========================

if [ ! -f "${MODEL}" ]; then
    echo "Model not found: ${MODEL}"
    exit 1
fi

if [ ! -f "${DATA_YAML}" ]; then
    echo "Dataset YAML not found: ${DATA_YAML}"
    exit 1
fi


# =========================
# (1) Character Detection
# =========================

echo "(1) Character Detection"

python ./detection/test.py \
    --model ${MODEL} \
    --data ${DATA_YAML}


# =========================
# (2) Character Cropping
# =========================

echo "(2) Character Cropping"

python ./crop/run.py \
    --image_dir ${IMAGE_DIR} \
    --labels_dir ${DET_OUTPUT}/labels \
    --save_root ${CROP_OUTPUT}


# =========================
# (3) Character Classification
# =========================

echo "(3) Character Classification"

python ./classification/run.py \
    --root_dir ${CROP_OUTPUT}/crops \
    --out_dir ${CLS_OUTPUT} \
    --batch_size 1280


# =========================
# (4) Character Ordering
# =========================

echo "(4) Character Ordering"

python ./ordering/run_ours.py \
    --input_dir ${CLS_OUTPUT} \
    --output_dir ${ORDER_OUTPUT}


# =========================
# (5) CER Evaluation
# =========================

if [ "$RUN_EVAL" = "true" ]; then
    echo "(5) CER Evaluation"

    python ./ordering/evaluate.py \
        --gt_dir ./ordering/gt \
        --pred_dir ${ORDER_OUTPUT} \
        --out_csv ${ORDER_CSV}
fi


# =========================
# Runtime
# =========================

END_TIME=$(date +%s)
TOTAL_TIME=$((END_TIME - START_TIME))

echo "Pipeline Finished"
echo "Final TXT results are saved in: ${ORDER_OUTPUT}"
echo "Total Pipeline Time: ${TOTAL_TIME} sec"


# =========================
# Peak GPU Memory
# =========================

if [[ "$MONITOR_GPU" = "true" ]]; then
    kill ${GPU_MONITOR_PID} 2>/dev/null || true
    GPU_MONITOR_PID=""
    trap - EXIT

    PEAK_GPU_MEMORY_MB=$(sort -nr ${GPU_MEMORY_LOG} | head -n 1)
    PEAK_GPU_MEMORY_GB=$(awk "BEGIN {printf \"%.4f\", ${PEAK_GPU_MEMORY_MB}/1024}")

    echo "Peak GPU Memory Used: ${PEAK_GPU_MEMORY_GB} GB (${PEAK_GPU_MEMORY_MB} MiB)"
fi
